sale_wal:
  outputs:
    dev:
      dataset: w_sal
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: D:\GCP practice\AIclass_2024\gcp_service_account\superb-reporter-430115-t3-d11fb568533d.json
      location: US
      method: service-account
      priority: interactive
      project: superb-reporter-430115-t3
      threads: 4
      type: bigquery
  target: dev
sales_prediction:
  outputs:
    dev:
      dataset: sales_inv_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: D:\GCP practice\AIclass_2024\gcp_service_account\superb-reporter-430115-t3-d11fb568533d.json
      location: US
      method: service-account
      priority: interactive
      project: superb-reporter-430115-t3
      threads: 4
      type: bigquery
  target: dev
